// Generated by CoffeeScript 2.3.1
(function() {
  /*
   0000000   0000000   000   000  00000000  000   0000000 
  000       000   000  0000  000  000       000  000      
  000       000   000  000 0 000  000000    000  000  0000
  000       000   000  000  0000  000       000  000   000
   0000000   0000000   000   000  000       000   0000000 
  */
  var _, fs, log, noon, obj, path, slash;

  ({slash, fs, noon, log, _} = require('kxk'));

  path = function(key, p, opt) {
    var o, ref;
    while (slash.dir(p).length && ((ref = slash.dir(p)) !== '.' && ref !== '/')) {
      p = slash.dir(p);
      if (fs.existsSync(slash.join(p, '.konrad.noon'))) {
        o = _.defaultsDeep(noon.load(slash.join(p, '.konrad.noon')), opt);
        if (o[key] != null) {
          return slash.resolve(p);
        }
      }
    }
    return null;
  };

  obj = function(p, opt) {
    var o, ref, ref1;
    while (slash.dir(p).length && ((ref1 = slash.dir(p)) !== '.' && ref1 !== '/') && !/^\w\:\/$/.test(slash.dir(p))) {
      p = slash.dir(p);
      if (fs.existsSync(slash.join(p, '.konrad.noon'))) {
        o = _.defaultsDeep(noon.load(slash.join(p, '.konrad.noon')), opt);
        if (((ref = o.ignore) != null ? ref.map : void 0) != null) {
          o.ignore = o.ignore.map(function(i) {
            if (_.isString(i)) {
              return new RegExp(i);
            } else {
              return i;
            }
          });
        }
        return o;
      }
    }
    return opt;
  };

  module.exports = {
    path: path,
    obj: obj
  };

}).call(this);
