// Generated by CoffeeScript 1.12.7

/*
00000000  00000000   00000000    0000000   00000000
000       000   000  000   000  000   000  000   000
0000000   0000000    0000000    000   000  0000000
000       000   000  000   000  000   000  000   000
00000000  000   000  000   000   0000000   000   000
 */

(function() {
  var konradError, log, pretty, slash;

  slash = require('kxk').slash;

  log = console.log;

  pretty = require('./pretty');

  konradError = function(title, msg, srcFile) {
    var col, errStr, file, fileLine, line, ref, ref1, rest, sourceFile, splitted, stripped;
    stripped = String(msg).strip;
    splitted = stripped.split('\n');
    if (title === 'compile error') {
      ref = splitted[0].split(': '), fileLine = ref[0], rest = ref[1];
      ref1 = slash.splitFileLine(fileLine), file = ref1[0], line = ref1[1], col = ref1[2];
      splitted[0] = rest.bold.yellow;
      errStr = splitted.join('\n');
      if (srcFile) {
        file = slash.tilde(srcFile);
      }
      sourceFile = file;
      if (line) {
        sourceFile += ":" + line;
      }
      if (col) {
        sourceFile += ":" + col;
      }
      log(pretty.time(), "😡  " + (pretty.filePath(sourceFile)) + "\n" + errStr);
    } else {
      log(title.bold.yellow + " " + (String(stripped).red));
    }
    return false;
  };

  module.exports = konradError;

}).call(this);
