// Generated by CoffeeScript 2.2.2
(function() {
  /*
  00000000  00000000   00000000    0000000   00000000
  000       000   000  000   000  000   000  000   000
  0000000   0000000    0000000    000   000  0000000
  000       000   000  000   000  000   000  000   000
  00000000  000   000  000   000   0000000   000   000
  */
  var konradError, log, pretty, slash;

  ({slash} = require('kxk'));

  log = console.log;

  pretty = require('./pretty');

  konradError = function(title, msg, srcFile) {
    var col, errStr, file, fileLine, line, rest, sourceFile, splitted, stripped;
    stripped = String(msg).strip;
    splitted = stripped.split('\n');
    if (title === 'compile error') {
      [fileLine, rest] = splitted[0].split(': ');
      [file, line, col] = slash.splitFileLine(fileLine);
      splitted[0] = rest.bold.yellow;
      errStr = splitted.join('\n');
      if (srcFile) {
        file = slash.tilde(srcFile);
      }
      sourceFile = file;
      if (line) {
        sourceFile += `:${line}`;
      }
      if (col) {
        sourceFile += `:${col}`;
      }
      log(pretty.time(), `😡  ${pretty.filePath(sourceFile)}\n${errStr}`);
    } else {
      log(`${title.bold.yellow} ${(String(stripped).red)}`);
    }
    return false;
  };

  module.exports = konradError;

}).call(this);
