// Generated by CoffeeScript 2.3.1
(function() {
  /*
   0000000  000   000   0000000   000   000  000      0000000  
  000       000   000  000   000  000   000  000      000   000
  0000000   000000000  000   000  000   000  000      000   000
       000  000   000  000   000  000   000  000      000   000
  0000000   000   000   0000000    0000000   0000000  0000000  
  */
  var _, argDir, args, colors, log, pretty, should, slash;

  ({args, slash, colors, log, _} = require('kxk'));

  argDir = require('./argdir');

  pretty = require('./pretty');

  should = function(k, o, p) {
    var i, j, keys, len, r;
    if (o[k] == null) {
      return false;
    }
    if (_.isArray(o[k])) {
      keys = o[k];
    } else if (_.isObject(o[k])) {
      keys = _.keys(o[k]);
    } else {
      keys = [o[k]];
    }
    for (j = 0, len = keys.length; j < len; j++) {
      i = keys[j];
      r = i;
      if (_.isString(i)) {
        r = new RegExp(i);
      }
      if (r.test(p)) {
        if (args.debug) {
          log(pretty.filePath(slash.relative(p, argDir()), colors.gray), 'should '.blue + k.bold.blue);
        }
        return true;
      }
    }
    return false;
  };

  module.exports = should;

}).call(this);
