// Generated by CoffeeScript 2.2.2
(function() {
  /*
  000000000   0000000   00000000    0000000   00000000  000000000
     000     000   000  000   000  000        000          000   
     000     000000000  0000000    000  0000  0000000      000   
     000     000   000  000   000  000   000  000          000   
     000     000   000  000   000   0000000   00000000     000   
  */
  var _, argDir, args, colors, config, log, slash, target;

  ({args, slash, colors, log, _} = require('kxk'));

  argDir = require('./argdir');

  config = require('./config');

  target = function(sourceFile, opt) {
    var ext, i, k, len, matches, o, r, ref, ref1, ref2, ref3, ref4, targetFile, v;
    ext = slash.ext(sourceFile);
    o = config.obj(sourceFile, opt);
    if (((ref = o[ext]) != null ? ref.filter : void 0) != null) {
      matches = false;
      ref1 = o[ext].filter;
      for (i = 0, len = ref1.length; i < len; i++) {
        r = ref1[i];
        if (new RegExp(r).test(sourceFile)) {
          matches = true;
        }
      }
      if (!matches) {
        if (args.debug) {
          log(pretty.filePath(slash.relative(sourceFile, argDir()), colors.blue));
        }
        return;
      }
    }
    targetFile = _.clone(sourceFile);
    if (((ref2 = o[ext]) != null ? ref2.replace : void 0) != null) {
      ref3 = o[ext].replace;
      for (k in ref3) {
        v = ref3[k];
        targetFile = targetFile.replace(k, v);
      }
    }
    if (((ref4 = o[ext]) != null ? ref4.ext : void 0) == null) {
      return;
    }
    return targetFile = slash.join(slash.dir(targetFile), slash.base(targetFile) + '.' + o[ext].ext);
  };

  module.exports = target;

}).call(this);
