// Generated by CoffeeScript 2.2.2
(function() {
  /*
  000   000   0000000   000      000   000
  000 0 000  000   000  000      000  000 
  000000000  000000000  000      0000000  
  000   000  000   000  000      000  000 
  00     00  000   000  0000000  000   000
  */
  var _, argDir, config, error, log, should, slash, target, walk, walkdir,
    indexOf = [].indexOf;

  ({walkdir, slash, error, log, _} = require('kxk'));

  argDir = require('./argdir');

  should = require('./should');

  target = require('./target');

  config = require('./config');

  walk = function(wlk, opt, cb) {
    var err;
    if (_.isFunction(opt)) {
      cb = opt;
      opt = {};
    }
    try {
      return walkdir.sync(argDir(), function(wp) {
        var o, p, ref;
        p = slash.path(wp);
        o = config.obj(p, opt);
        if (should('ignore', o, p)) {
          if (opt.all) {
            cb(p);
          }
          this.ignore(wp);
          return;
        }
        if (should('ignore', wlk, p)) {
          if (opt.all) {
            cb(p);
          }
          this.ignore(wp);
          return;
        }
        if (ref = slash.ext(p), indexOf.call(_.keys(o), ref) >= 0) {
          return cb(p, target(p, opt));
        } else {
          if (opt.all) {
            if (!cb(p)) {
              return this.ignore(wp);
            }
          }
        }
      });
    } catch (error1) {
      err = error1;
      return error("walk", err);
    }
  };

  module.exports = walk;

}).call(this);
